language: python
before_install:
  - pip install pycodestyle
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
  - pytest --cov=solstice
after_success:
  - coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: RXW48clv+EQ+GdK9Vg+yIht1MFOj7qJrH4l7dtLHjf1ocgJjU/erBWXnGKuj3jyM5GRwuN611qPEIcAnQL4q8JDEJl0GuY0BjeHNaBdBKlCOx9lAQ+4912H7qojPhewyCEFOhe7ELJV54ytq5K0PX5U2HVcbevWxXueUX2EGKAZSiOxVB99EWlZ29u9MRzjfsik2Ktez2U8H1+UTR22e1s1t49x93334eKvWUQNxTvtYZa71bl4UxTl6AiLsm5y/T0ZTylj3QqOFFig+JR5z0or8EcWvz6xXB1nRiineRdssliXYRsH/ru8F250Ch+DBXxUxN8l6fBaxpZ0usNEGvPNuc1vbiM7In2xYH16oCNjbPE4SfP2BJnMGJ6oMMBwvH6f3EwvcwnDedrdo5pkpgBHQRRXNWqxlWu1NXhNwmFeAhCZOZUL88DyWq9b5QZW1BE96qrXBTdt6WBHyNjfsTcZ1dY5l/i3+vjsxgx1p502WvMPsu9FQW0A75HZQnbItxgeTWME19FmpybYXMYqbzwM138OFkGLXI1weVOe4XLaT72tv0bIWa+byI1aM696TkYuxEggGr0Z3v+LI997MtDi725+kbhe/O6icqgtEuV+Jds0QuKxQjHphFFCr5ejgeskjmhR6X2MVkb7/eLB1ZpCnAC+1s/UfHS4+hJpSCEA=
  on:
    branch: master
    tags: true